// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAha_NIL5wRhVHvZp5zOmTltBLuvAro4AE',
    appId: '1:974432764802:web:cd35ced8a0fa32f18d859b',
    messagingSenderId: '974432764802',
    projectId: 'todoapplicationadv',
    authDomain: 'todoapplicationadv.firebaseapp.com',
    storageBucket: 'todoapplicationadv.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpngrSP2hLdF9f97Z9UMNtjh8tK5SQw1M',
    appId: '1:974432764802:android:a46aaa4d7892ad3e8d859b',
    messagingSenderId: '974432764802',
    projectId: 'todoapplicationadv',
    storageBucket: 'todoapplicationadv.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmbYbeLIuehlsrTRHAKiyg4jfXkU_7v2w',
    appId: '1:974432764802:ios:44873499e31f3fa78d859b',
    messagingSenderId: '974432764802',
    projectId: 'todoapplicationadv',
    storageBucket: 'todoapplicationadv.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmbYbeLIuehlsrTRHAKiyg4jfXkU_7v2w',
    appId: '1:974432764802:ios:44873499e31f3fa78d859b',
    messagingSenderId: '974432764802',
    projectId: 'todoapplicationadv',
    storageBucket: 'todoapplicationadv.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAha_NIL5wRhVHvZp5zOmTltBLuvAro4AE',
    appId: '1:974432764802:web:f2358cb8777c5be18d859b',
    messagingSenderId: '974432764802',
    projectId: 'todoapplicationadv',
    authDomain: 'todoapplicationadv.firebaseapp.com',
    storageBucket: 'todoapplicationadv.firebasestorage.app',
  );

}